services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: bedautomation_postgres
    environment:
      POSTGRES_DB: BedAutomation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bedautomation_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ASP.NET Core Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bedautomation_web
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=BedAutomation;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - bedautomation_network
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
    driver: local

networks:
  bedautomation_network:
    driver: bridge 